apiVersion: v2
name: gretel-data-plane
description: A chart for running on premise Gretel workflows
type: application
version: 0.0.4
appVersion: "0.0.4"
icon: "https://avatars.githubusercontent.com/u/59622948?s=200&v=4"
