apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}worker-limit
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: workers
    {{- include "gretel-gcc.labels" . | nindent 4 }}
  annotations:
    workflows.argoproj.io/description: |
      This is the maximum number of argo-workflows Workflows that can be created in the namespace.
spec:
  hard:
    count/workflows.argoproj.io: {{ .Values.gretelWorkers.limits.maxTotalWorkflows | quote }}
