{{- if .Values.gretelAgent._enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}agent-rolebinding
  labels:
    app.kubernetes.io/component: agent
    {{- include "gretel-gcc.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "gretel-gcc.gretelAgent.serviceAccount.name" . }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gretel-gcc.namePrefix" . }}agent-role
{{- end }}
