{{- if .Values.gretelAgent._enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}agent-secret
  labels:
    app.kubernetes.io/component: agent
    {{- include "gretel-gcc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.gretelConfig.apiKeySecretRef }}
  GRETEL_API_KEY: {{ required "gretelConfig.apiKey must be set!" .Values.gretelConfig.apiKey }}
  {{- end }}
  GRETEL_ENDPOINT: "{{ .Values.gretelConfig.apiEndpoint }}"
{{- end }}
