{{- if .Values.gretelAgent._enabled }}
{{- if .Values.gretelAgent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "gretel-gcc.gretelAgent.serviceAccount.name" . }}"
  labels:
    app.kubernetes.io/component: agent
    {{- include "gretel-gcc.labels" . | nindent 4 }}
  {{- with .Values.gretelAgent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.gretelWorkers.model.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "gretel-gcc.gretelWorkers.model.serviceAccount.name" . }}"
  labels:
    app.kubernetes.io/component: agent
    {{- include "gretel-gcc.labels" . | nindent 4 }}
  {{- with .Values.gretelWorkers.model.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
