{{- if .Values.gretelAgent._enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}agent
  labels:
    app.kubernetes.io/component: agent
    {{- include "gretel-gcc.labels" . | nindent 4 }}
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 8080
      targetPort: prometheus-port
  selector:
    {{- include "gretel-gcc.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
    workload: agent
{{- end }}
