{{- if .Values.gretelConfig.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}controller-secret
  labels:
    app.kubernetes.io/component: controller
    {{- include "gretel-gcc.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.gretelConfig.apiKey }}
{{- end }}
