{{- if .Values.gretelController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "gretel-gcc.gretelController.serviceAccount.name" . }}"
  labels:
    app.kubernetes.io/component: controller
    {{- include "gretel-gcc.labels" . | nindent 4 }}
  {{- with .Values.gretelController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.gretelWorkers.workflow.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "gretel-gcc.gretelWorkers.workflow.serviceAccount.name" . }}"
  labels:
    app.kubernetes.io/component: controller
    {{- include "gretel-gcc.labels" . | nindent 4 }}
  {{- with .Values.gretelWorkers.workflow.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
