apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gretel-hybrid
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: gretel-hybrid
  source:
    chart: gretel-data-plane
    repoURL: https://gretel-blueprints-pub.s3.us-west-2.amazonaws.com/helm-charts/stable
    targetRevision: 0.0.4
    helm:
      releaseName: gretel-data-plane
      values: |
        {{- include "gretel-data-plane.values" . | nindent 8 }}
