apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}argo-config
  labels:
    {{- include "gretel-gcc.labels" . | nindent 4 }}
    app.kubernetes.io/component: argo-controller
data:
  {{- $argoConfig := deepCopy .Values.argoConfig }}
  {{- $_ := include "gretel-gcc.argoArtifactRepository" . | set $argoConfig "artifactRepository" }}
  {{- range $k, $v := $argoConfig }}
  {{- if not (kindIs "string" $v) }}
  {{- $v = toYaml $v }}
  {{- end }}
  {{ $k }}: |-
    {{- $v | nindent 4 }}
  {{- end }}
