{{- if .Values.argoController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "gretel-gcc.argoController.serviceAccount.name" . }}"
  labels:
    app.kubernetes.io/component: argo-controller
    {{- include "gretel-gcc.labels" . | nindent 4 }}
  {{- with .Values.argoController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
