# Default values for gretel-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Common parameters
## @descripton Parameters that are not unique to this chart
## Gretel agents image version
## ref: https://gallery.ecr.aws/gretelai/gretel-k8s-agent
## @param image.repository Public Gretel ECR repository and registry
## @param image.pullPolicy Policy on how often to pull the image
## @param image.tag Agent image tag
image:
  repository: "public.ecr.aws/gretelai/gretel-k8s-agent"
  pullPolicy: IfNotPresent
  tag: ""

## String to override the name of this chart and its resources
## @param nameOverride String to partially override the name of the chart and resources
nameOverride: ""
## String to fully override gretel-agent.fullname template
## @param fullnameOverride String to fully override gretel-agent.fullname
##
fullnameOverride: ""

## Service account configuration, used for workers and agent pod
##
## @param serviceAccount.create Enable creation of this service account. Note: pods will fail to start if no service account exists
## @param serviceAccount.name Name of the service account
## @param serviceAccount.annotations Annotations needed by the service account, maybe for some type of IAM access
##
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "gretel-agent"

## Any pod annotations applied to the agent pod
## @param podAnnotations Annotations for the agent pod
podAnnotations: {}

## Security context for the agent pod
## @param podSecurityContext Security context for the agent pod
podSecurityContext:
  {}
  # fsGroup: 2000

## Security context for the agent containers
## @param securityContext Security context for the agent containres
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## Agent resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
## @param resources.limits.memory  The resources memory limits for the agent container
## @param resources.requests.cpu  The requested cpu resources for the agent container
## @param resources.requests.memory  The requested memory resources for the agent container
##
resources:
  limits:
    memory: 528Mi
  requests:
    cpu: "0.5"
    memory: 528Mi
## The node selector for the agent pod
## @param nodeSelector The node selector for the agent pod
nodeSelector: {}

## The list of tolerations for the agent pod
## @param tolerations The list of tolerations for the agent pod
tolerations: []

## The affinity for the agent pod
## @param affinity The affinity for the agent pod
affinity: {}

## @section Gretel Parameters
## @descripton Parameters that are not unique to this chart
## Kubewatch containers' liveness probe.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
##
## @param gretelConfig.artifactEndpoint S3/GCS/Azure storage path, used to upload model related artifacts
## @param gretelConfig.apiEndpoint API endpoint to receive Gretel Jobs
## @param gretelConfig.apiKey Key used to authenticate to the Gretel API. Only one of apiKey or apiKeySecretRef should be set.
## @param gretelConfig.apiKeySecretRef Existing kubernetes secret where GRETEL_API_KEY is set. Allows passing the API key via CSI provider. Only one of apiKey or apiKeySecretRef should be set.
## @param gretelConfig.project Project to receive jobs from
## @param gretelConfig.workerEnv Environment variables to be passed to the worker pods
## @param gretelConfig.workerMemoryInGb Memory size in GB for the worker pods
## @param gretelConfig.maxWorkers Number of workers to spawn concurrently from the agent
## @param gretelConfig.gpuNodeSelector Node selector for selecting GPUs based jobs
## @param gretelConfig.cpuNodeSelector Node selector for selecting CPU based jobs
## @param gretelConfig.gpuTolerations Tolerations for GPU based jobs
## @param gretelConfig.cpuTolerations Tolerations for CPU based jobs
## @param gretelConfig.cpuCount Integer value specifying number of CPUs to use for workers
## @param gretelConfig.extraCaCert PEM certificate file contents to be used by the agent/workers
## @param gretelConfig.imageRegistryOverrideHost URL to override the image registry used to fetch worker images
## @param gretelConfig.preventAutoscalerEviction Adds an annotation to Gretel jobs to prevent being evicted by the autoscaler
## @param gretelConfig.podLabels Labels to apply to Pods deployed by this chart
## @param gretelConfig.deploymentLabels Labels to apply to Deployments deployed by this chart
##
gretelConfig:
  artifactEndpoint: ""
  apiEndpoint: "https://api.gretel.cloud"
  apiKey: ""
  apiKeySecretRef: ""
  project: ""
  workerEnv: # Any required environment variables for object storage should either go here or be set using --set gretelConfig.workerEnv.VAR_NAME=VAR_VALUE
  workerMemoryInGb: 14
  maxWorkers: 0
  gpuNodeSelector: {}
  cpuNodeSelector: {}
  gpuTolerations: []
  cpuTolerations: []
  cpuCount: ""
  extraCaCert: ""
  imageRegistryOverrideHost: ""
  preventAutoscalerEviction: true
  podLabels: {}
  deploymentLabels: {}
