{{ if .Values.gretelConfig.extraCaCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "gretel-agent.extraCaCertConfigmapName" . }}"
  labels:
    {{- include "gretel-agent.labels" . | nindent 4 }}
data:
  ca.crt: |
    {{ .Values.gretelConfig.extraCaCert | nindent 4 }}
{{ end }}