apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gretel-agent.fullname" . }}-environment-configmap
  labels:
    {{- include "gretel-agent.labels" . | nindent 4 }}
data:
  GRETEL_WORKER_NAMESPACE: {{ .Release.Namespace }}
  MEMORY_LIMIT_IN_GB: "{{ .Values.gretelConfig.workerMemoryInGb }}"
  GRETEL_PULL_SECRET: gretel-pull-secret
  GRETEL_WORKER_SA: {{ include "gretel-agent.serviceAccountName" . }}
  GRETEL_WORKER_SECRET_NAME:  {{ include "gretel-agent.workerSecretName" . }}
  GPU_NODE_SELECTOR:  {{ .Values.gretelConfig.gpuNodeSelector | toJson | quote }}
  CPU_NODE_SELECTOR:  {{ .Values.gretelConfig.cpuNodeSelector | toJson | quote }}
  GPU_TOLERATIONS:  {{ .Values.gretelConfig.gpuTolerations | toJson | quote }}
  CPU_TOLERATIONS:  {{ .Values.gretelConfig.cpuTolerations | toJson | quote }}
  GPU_WORKER_SECURITY_CONTEXT: {{ .Values.gretelConfig.gpuSecurityContext | toJson | quote }}
  CPU_WORKER_SECURITY_CONTEXT: {{ .Values.gretelConfig.cpuSecurityContext | toJson | quote }}
  GRETEL_CPU_COUNT:  "{{ .Values.gretelConfig.cpuCount }}"
  {{- if .Values.gretelConfig.extraCaCert }}
  GRETEL_CA_CERT_CONFIGMAP_NAME: {{ include "gretel-agent.extraCaCertConfigmapName" . }}
  {{- end }}
  IMAGE_REGISTRY_OVERRIDE_HOST: "{{ .Values.gretelConfig.imageRegistryOverrideHost }}"
  PREVENT_AUTOSCALER_EVICTION: "{{ .Values.gretelConfig.preventAutoscalerEviction }}"
  {{- if .Values.gretelConfig.project }}
  GRETEL_PROJECT: "{{ .Values.gretelConfig.project }}"
  GRETEL_DEFAULT_PROJECT: "{{ .Values.gretelConfig.project }}"
  {{- end }}
  GRETEL_ARTIFACT_ENDPOINT: {{ required ".Values.gretelConfig.artifactEndpoint must be set!" .Values.gretelConfig.artifactEndpoint }}
  RUNNER_MODES: "hybrid manual"
  GRETEL_RUNNER_MODE: "hybrid"
