kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: launch-jobs
  namespace: "{{.Release.Namespace}}"
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods", "secrets"]
    verbs: ["delete", "create", "patch", "get", "update", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: launch-jobs
  namespace: "{{.Release.Namespace}}"
subjects:
  - kind: ServiceAccount
    name: '{{include "gretel-agent.serviceAccountName" .}}'
    namespace: "{{.Release.Namespace}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: launch-jobs
