apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gretel-agent.secretName" . }}
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  {{- if .Values.gretelConfig.apiKey }}
  GRETEL_API_KEY: {{ .Values.gretelConfig.apiKey }}
  {{- end }}
  GRETEL_ENDPOINT: "{{ .Values.gretelConfig.apiEndpoint }}"
  {{- with .Values.gretelConfig.workerEnv }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
