apiVersion: v1
kind: Service
metadata:
  name: {{include "gretel-agent.fullname" .}}
  namespace: {{.Release.Namespace}}
  labels:
  {{- include "gretel-agent.labels" . | nindent 4}}
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: 8080
      targetPort: prometheus-port
  selector:
      {{- include "gretel-agent.selectorLabels" . | nindent 6 }}