apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gretel-agent.workerSecretName" . }}
  namespace: "{{ .Release.Namespace }}"
type: Opaque
stringData:
  {{- with .Values.gretelConfig.workerEnv }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
