apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}common-data-secret
  labels:
    app.kubernetes.io/component: common
    {{- include "gretel-gcc.labels" . | nindent 4 }}
stringData:
  {{- with .Values.gretelConfig.caOverride }}
  {{- if not (regexMatch "^(\\s*\\n)?(-----BEGIN CERTIFICATE-----\\s*\\n[a-zA-Z0-9+/\\s]+(\\s*=\\s*){0,2}\\n-----END CERTIFICATE-----\\s*(\\n|$))+$" .) }}
  {{- fail "gretelConfig.caOverride must be a list of PEM-encoded certificates" }}
  {{- end }}
  ca-override.pem: |
    {{- . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gretel-gcc.namePrefix" . }}common-env-secret
  labels:
    app.kubernetes.io/component: common
    {{- include "gretel-gcc.labels" . | nindent 4 }}
stringData:
  GRETEL_COMMON_ENV_SECRET_NAME: {{ include "gretel-gcc.namePrefix" . }}common-env-secret
  GRETEL_COMMON_DATA_SECRET_NAME: {{ include "gretel-gcc.namePrefix" . }}common-data-secret
  GRETEL_COMMON_DATA_MOUNT_PATH: {{ include "gretel-gcc.commonData.mountPath" . }}
  GRETEL_CHART_VERSION: {{ .Chart.Version }}
  GRETEL_APP_VERSION: {{ .Chart.AppVersion }}
  GRETEL_TOOLS_BUCKET: {{ .Values.gretelConfig.toolsBucketEndpoint }}
  {{- if .Values.gretelConfig.caOverride }}
  SSL_CERT_FILE: {{ include "gretel-gcc.commonData.mountPath" . }}/ca-override.pem
  REQUESTS_CA_BUNDLE: {{ include "gretel-gcc.commonData.mountPath" . }}/ca-override.pem
  {{- end }}
  {{- with .Values.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
