{{- $llmConfig := fromYaml (include "validateAndGetModelConfig" .) }}

{{- if .Values.gretelInitImage.enabled  }}
{{- if and .Values.gretelConfig.apiKey .Values.gretelConfig.apiKeySecretRef }}
{{ fail "Both .gretelConfig.apiKey and .gretelConfig.apiKeySecretRef cannot be set. Only set one of these values." }}
{{- else if (not (or .Values.gretelConfig.apiKey .Values.gretelConfig.apiKeySecretRef)) -}}
{{ fail "One of .gretelConfig.apiKey or .gretelConfig.apiKeySecretRef must be set" }}
{{- end -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gretel-inference-llm.llmName" . }}
  labels:
    {{- include "gretel-inference-llm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gretel-inference-llm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gretel-inference-llm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.gretelInitImage.enabled }}
      initContainers:
        - name: "{{ .Values.gretelInitImage.name }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gretelInitImage.repository }}:{{ .Values.gretelInitImage.tag }}"
          env:
          - name: MODEL_BUCKET
            value: "{{ $llmConfig.modelBucket }}"
          - name: MODEL_ID
            value: "{{ $llmConfig.modelId }}"
          - name: GRETEL_ENDPOINT
            value: "{{ .Values.gretelConfig.apiEndpoint }}"
          {{- with (include "gretel-inference-llm.gretelConfig.apiKeySecretName" .) }}
          - name: GRETEL_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ . | quote }}
                key: GRETEL_API_KEY
          {{- end }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -euo pipefail;
              curl --header "Authorization: $GRETEL_API_KEY" "$GRETEL_ENDPOINT/opt/inference_models/get_credentials" | tr -d '"' > /tmp/out.env;
              source /tmp/out.env;
              aws s3 cp --recursive s3://${MODEL_BUCKET}/${MODEL_ID} /models/${MODEL_ID};
          volumeMounts:
            - mountPath: /models
              name: models
            - mountPath: /tmp
              name: tmp
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      containers:
        - name: {{ include "gretel-inference-llm.llmName" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gretelLLMImage.repository }}:{{ .Values.gretelLLMImage.tag }}"
          imagePullPolicy: {{ .Values.gretelLLMImage.pullPolicy }}
          env:
          - name: PORT
            value: "{{ .Values.service.port }}"
          - name: MODEL_ID
            value: "/models/{{ $llmConfig.modelId }}"
          - name: MAX_TOTAL_TOKENS
            value: "{{ $llmConfig.maxTotalTokens }}"
          - name: MAX_INPUT_LENGTH
            value: "{{ $llmConfig.maxInputLength }}"
          - name: MAX_CONCURRENT_REQUESTS
            value: "{{ $llmConfig.maxConcurrentRequests }}"
          - name: TRUST_REMOTE_CODE
            value: "{{ $llmConfig.trustRemoteCode }}"
          - name: HUGGINGFACE_HUB_CACHE
            value: "/tmp"
          - name: NUMBA_CACHE_DIR
            value: "/tmp"
          {{- with $llmConfig.quantize }}
          - name: "QUANTIZE"
            value: "{{ . }}"
          {{- end}}
          {{- with $llmConfig.ropeScaling }}
          - name: "ROPE_SCALING"
            value: "{{ . }}"
          {{- end}}
          {{- with $llmConfig.ropeFactor }}
          - name: "ROPE_FACTOR"
            value: "{{ . }}"
          {{- end}}
          {{- with $llmConfig.maxBatchPrefillTokens }}
          - name: "MAX_BATCH_PREFILL_TOKENS"
            value: "{{ . }}"
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /dev/shm
              name: shm
            {{- if .Values.gretelInitImage.enabled }}
            - mountPath: /models
              name: models
            {{- end }}
            - mountPath: /tmp
              name: tmp
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        {{- if .Values.gretelInitImage.enabled }}
        - name: models
          emptyDir:
            sizeLimit: {{ $llmConfig.modelSize }}Gi
        {{- end }}
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
