{{- if .Values.gretelConfig.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gretel-inference-llm.appName" . }}-gretel-api-key
  labels:
    {{- include "gretel-inference-llm.labels" . | nindent 4 }}
type: Opaque
stringData:
  GRETEL_API_KEY: {{ .Values.gretelConfig.apiKey }}
{{- end }}
